name: Python Linting with Black

on:
  pull_request:
    types: [ opened, reopened, synchronize, edited ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Get modified files
      id: get_files
      run: echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.py$' || true)"
    
    - name: Lint with Black
      run: |
        if [ -n "${{ steps.get_files.outputs.files }}" ]; then
          black --check ${{ steps.get_files.outputs.files }}
        else
          echo "No Python files modified."
        fi

      continue-on-error: true

    - name: Generate annotations
      if: ${{ failure() }}
      run: |
        if [ -n "${{ steps.get_files.outputs.files }}" ]; then
          while IFS= read -r file; do
            errors=$(black --check "$file" | awk -F ":" '{print $3":"$4}')
            IFS=$'\n' read -rd '' -a errors_array <<<"$errors"
            for err in "${errors_array[@]}"; do
              IFS=: read -r line col <<<"$err"
              echo "::error file=${file},line=${line},col=${col}::Black formatting issue found in ${file}."
            done
          done <<<"${{ steps.get_files.outputs.files }}"
        fi
