name: Python Linting with Black

on:
  pull_request:
    types: [ opened, reopened, synchronize, edited ]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: python linters
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install linter dependencies
        run: |
          python -m pip install pip==22.2.2
          pip install -r requirements-lint.txt
      - name: Check for python file changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: 'shell'
          filters: |
            py_scripts_filter:
              - added|modified: '**/*.py'
      - name: Run linter
        if: ${{ steps.filter.outputs.py_scripts_filter == 'true' }}
        run: |
          echo "Changed python files: ${{ steps.filter.outputs.py_scripts_filter_files }}"
          lint_output_formatted=$(echo "${lint_output}" | jq -s -R @csv)
          black_output_formatted=$(echo "${black_output}" | jq -s -R @csv)
          isort_output_formatted=$(echo "${isort_output}" | jq -s -R @csv)

          # Debugging: Print linting outputs
          echo "FLAKE8_OUTPUT=${lint_output}"
          echo "BLACK_OUTPUT=${black_output}"
          echo "ISORT_OUTPUT=${isort_output}"

          # FLAKE8 linting
          if [ -n "${lint_output}" ]; then
            lint_output_lines="${lint_output}"
            echo "::error file=${{ steps.filter.outputs.py_scripts_filter_files }}::${lint_output_lines}"
          fi

          # BLACK linting
          if [ -n "${black_output}" ]; then
            black_output_lines="${black_output}"
            echo "::error file=${{ steps.filter.outputs.py_scripts_filter_files }}::${black_output_lines}"
          fi

          # ISORT linting
          if [ -n "${isort_output}" ]; then
            isort_output_lines="${isort_output}"
            echo "::error file=${{ steps.filter.outputs.py_scripts_filter_files }}::${isort_output_lines}"
          fi

          # Fail the job if there are any errors
          if [ -n "${lint_output}" ] || [ -n "${black_output}" ] || [ -n "${isort_output}" ]; then
            exit 1
          fi