name: CI testing

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        
        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: 3.11
        
        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '14'
        
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install black
        
        - name: Run Black Format Check
          run: |
            mkdir -p annotations
            black --check --diff . > annotations/black_changes.diff || true
        
        - name: Convert diff to annotations
          id: convert-diff
          run: |
            if [ -s annotations/black_changes.diff ]; then
                npx diff2html -s line-by-line -F annotations/black_changes.diff -o annotations/black_changes.html
            fi
        
        - name: Annotate Pull Request
          uses: yuzutech/annotations-action@v0.3.0
          if: steps.convert-diff.outputs.converted
          with:
            repo-token: "${{ secrets.GITHUB_TOKEN }}"
            title: "Black Format Check"
            input: "./annotations/black_changes.html"