name: Python Linting with Black

on:
  pull_request:
    types: [ opened, reopened, synchronize, edited ]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: python linters
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install linter dependencies
        run: |
          python -m pip install pip==22.2.2
          pip install -r requirements-lint.txt
      - name: Check for python file changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: 'shell'
          filters: |
            py_scripts_filter:
              - added|modified: '**/*.py'
      - name: Run linter
        if: ${{ steps.filter.outputs.py_scripts_filter == 'true' }}
        run: |
          echo "Changed python files: ${{ steps.filter.outputs.py_scripts_filter_files }}"
          lint_output=$(python -m flakeheaven lint zikkie-demo-trigger/lambda_function.py 2>&1) || true
          black_output=$(python -m black --check zikkie-demo-trigger/lambda_function.py 2>&1) || true
          isort_output=$(python -m isort --check zikkie-demo-trigger/lambda_function.py 2>&1) || true

          # Store lint outputs as environment variables
          echo "FLAKE8_OUTPUT=${lint_output}" >> $GITHUB_ENV
          echo "BLACK_OUTPUT=${black_output}" >> $GITHUB_ENV
          echo "ISORT_OUTPUT=${isort_output}" >> $GITHUB_ENV
      
      - name: Generate annotations
        if: ${{ steps.filter.outputs.py_scripts_filter == 'true' }}
        run: |
          # Check if there are linting errors and create annotations
          if [ -n "${{ env.FLAKE8_OUTPUT }}" ]; then
            echo "${{ env.FLAKE8_OUTPUT }}" | while read -r line; do
              IFS=: read -r filename lineno colno error <<<"$line"
              echo "::error file=${filename},line=${lineno},col=${colno}::${error}"
            done
          fi

          if [ -n "${{ env.BLACK_OUTPUT }}" ]; then
            echo "::error file=::${{ env.BLACK_OUTPUT }}"
          fi

          if [ -n "${{ env.ISORT_OUTPUT }}" ]; then
            echo "::error file=::${{ env.ISORT_OUTPUT }}"
          fi

          # Fail the job if there are any errors
          if [ -n "${{ env.FLAKE8_OUTPUT }}" ] || [ -n "${{ env.BLACK_OUTPUT }}" ] || [ -n "${{ env.ISORT_OUTPUT }}" ]; then
            exit 1
          fi