name: CI testing

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v2
          with:
            python-version: 3.9
        - run: |
            pip install black
            black --check .