name: Python Linting with Black

on:
  pull_request:
    types: [ opened, reopened, synchronize, edited ]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: python linters
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install linter dependencies
        run: |
          python -m pip install pip==22.2.2
          pip install -r requirements-lint.txt
      - name: Check for python file changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: 'shell'
          filters: |
            py_scripts_filter:
              - added|modified: '**/*.py'
      - name: Run linter
        if: ${{ steps.filter.outputs.py_scripts_filter == 'true' }}
        run: |
          black --check --diff "${{ steps.filter.outputs.py_scripts_filter_files