name: Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - zikke-demo-trigger/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Configure AWS CLI
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: Deploy lambda definitions
          run: |
            ./deploy.sh zikke-demo-trigger